language: objective-c
osx_image: xcode7
xcode_workspace: sync-ios-app.xcworkspace
xcode_scheme: sync-ios-app
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master
    - cocoapods