language: objective-c
osx_image: xcode7.3
xcode_workspace: sync-ios-app.xcworkspace
xcode_scheme: sync-ios-app
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master